name: ci

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'

jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: armv7
            platform: linux/arm/v7
          - arch: arm64
            platform: linux/arm64
          - arch: amd64
            platform: linux/amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2.3.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUBUNAME }}
          password: ${{ secrets.DOCKERHUBPWD }}

      - name: Cache Docker layers (GitHub cache backend)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: ${{ matrix.platform }}
          push: false
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
